#!/bin/sh -e

## from /usr/share/debhelper/autoscripts/postrm-systemd :

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask yggdrasil.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge yggdrasil.service >/dev/null
		deb-systemd-helper unmask yggdrasil.service >/dev/null
	fi

	# Remove user configurations
	rm -rf /etc/yggdrasil-go/conf.json
fi

exit 0
